#include "tries.h"

const string text="Keep a gold chain on my neck\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Keep a gold chain on my neck\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Keep a gold chain on my neck (keep up the chain)\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Keep a gold chain on my neck (keep up the chain)\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Rock the boat like a one-eyed pirate\n"
                  "Rick James, I get glitter on my eyelids\n"
                  "2 A.M., eighty-five on the highway\n"
                  "Whole world get a little misguided\n"
                  "Where the spotlight? Put me in the spotlight\n"
                  "Trust no one that put you in the wrong light\n"
                  "I scream when I hit her with the long pipe\n"
                  "Mmm, ice cream when I hit her with the sweet thang\n"
                  "Do my thing, no, I do not do speaking\n"
                  "Get my shot, point it out like whoop, bang\n"
                  "I'ma win a bitch and I got a mood swing\n"
                  "I'm the realest, bitch, now I got a mood swing\n"
                  "I got bipolar confidence\n"
                  "Wake up like \"shit\" then I feel like a shit\n"
                  "So I guess I'm the shit\n"
                  "Yeah, guess I'm the shit\n"
                  "Keep a gold chain on my neck\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Keep a gold chain on my neck\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Keep a gold chain on my neck (keep up the chain)\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Keep a gold chain on my neck (keep up the chain)\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Grab life by the horns when I whip the Lambo\n"
                  "Black on red like I work the sambo\n"
                  "Clip's so long it'll make you mumble\n"
                  "Watch you tangle, dutty wine\n"
                  "She grind on my dick like a hundred times\n"
                  "Shawty love me long when I grip your sides\n"
                  "You slip inside like a slip and slide\n"
                  "My electric eel, your electric slide but\n"
                  "I just wanna feel up the booty\n"
                  "All on me, all on me, all on me\n"
                  "We can slow clap like wooty\n"
                  "All on me, all on me, all on me\n"
                  "I just wanna feel on your booty\n"
                  "Grab the camcorder, we can make it a movie\n"
                  "Bring a friend with you if you like how I do it\n"
                  "Gold chain swingin', and she like how I shoot it\n"
                  "Keep a gold chain on my neck\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Keep a gold chain on my neck\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Keep a gold chain on my neck (keep up the chain)\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Keep a gold chain on my neck (keep up the chain)\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Damn\n"
                  "Damn, I'm frosty\n"
                  "Blood diamond, I'm flossing\n"
                  "Navy camel, I'm drowning\n"
                  "But you don't see what it cost me\n"
                  "Turn 'em on like the Saudis\n"
                  "Hand-me-downs never fit me\n"
                  "Party never fit me, punani never fit me\n"
                  "Damn, time travelin', Honda swervin', that's so Merlyn\n"
                  "That's so Merlyn\n"
                  "That's so Merlyn\n"
                  "That's so Merlyn\n"
                  "Damn, time travelin', Honda swervin', book learnin'\n"
                  "That's so Merlyn\n"
                  "That's so Merlyn\n"
                  "That's so Merlyn\n"
                  "Swan dived on the 405\n"
                  "Land at the bottom of Arturo High\n"
                  "With the precision of a cut from a Zorro knife\n"
                  "The boy spit like he made out of 409\n"
                  "So that's clean, bitch\n"
                  "You can't play with my team, bitch\n"
                  "We rock pink, no more Wednesdays\n"
                  "Wringler's good with your envy\n"
                  "Mix with white 'cause you salty\n"
                  "But this stainless\n"
                  "I'm like platinum and it's painless\n"
                  "I just skip on the beat like I'm Pee-Wee Herman\n"
                  "Hands off of all my sermons\n"
                  "My wheel's turnin', now I'm more efficient than ever\n"
                  "I feel like Ratatouille when I'm whipping that Chevy\n"
                  "You see, you better fucking get some sweaters 'cause this ice\n"
                  "Might fuck around and change your whole life\n"
                  "'Cause we about to take flight\n"
                  "Keep a gold chain on my neck\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Keep a gold chain on my neck\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Keep a gold chain on my neck (keep up the chain)\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Keep a gold chain on my neck (keep up the chain)\n"
                  "Fly as a jet\n"
                  "Boy, better treat me with respect\n"
                  "Keep a gold chain (wax, wax it)\n"
                  "I keep a gold chain (wax, wax it)\n"
                  "Keep a gold chain\n"
                  "(I said I keep a gold chain)\n"
                  "Keep a gold chain\n"
                  "(I keep a gold chain)\n"
                  "Keep a gold chain\n"
                  "'Cause then I keep a\n"
                  "(I keep a gold chain) a gold chain, keep a gold chain\n"
                  "(Keep a gold chain) I said I keep a, I keep a\n"
                  "(Keep a gold chain) (wax, wax it)";

int main() {
    auto tries = new Trie;
    /*tries->insert("Hola");
    tries->insert("como");
    tries->insert("Hola");
    tries->delete_word("Hola");
    cout<<tries->search_word("Hola")<<endl<<tries->search_prefixes("Hello").size();*/
    tries->insert_text(text);
    tries->delete_word("409");
    tries->print();
    return 0;
}